### PR TITLE
feat: Enable sprig template function library to webhook template render

### PR DESCRIPTION
**Pull request by toninis**
## Description

With this PR we enable [sprig](https://github.com/Masterminds/sprig) functions template library to the Webhook Template. 
This functionality is really helpful to our case as we are using the same configuration to multiple clusters with different versions and the node labels are not always the same. 

i.e. 
```
Instance Type:* `{{default (index .NodeLabels "node.kubernetes.io/instance-type") (index .NodeLabels "beta.kubernetes.io/instance-type") }}
``` 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bwagner5** [comment]
Hello! Thanks for contributing to NTH! I've glanced at the changes in the PR and everything looks pretty good, but please allow us some extra time to review since it does bring in several dependencies that we'll need to look into (we'll also be out until June 2nd for a US Holiday, Memorial Day). Thanks for your patience!

**Comment by imuqtadir** [comment]
LGTM! Thanks for the PR once again

**Review by bwagner5 — APPROVED** [review]
lgtm

**Comment by bwagner5** [comment]
I'll merge this PR at the same time the license PR is merged: https://github.com/aws/aws-node-termination-handler/pull/446

**Pull request merged**
