### PR TITLE
Old versions of k8s remove from testing

### PR DESCRIPTION
**Pull request by ngoyal16**
Issue #, if available: #507 

Description of changes: 
1. Removed old k8s versions from testing 
2. Added new k8s version 1.22 in testing
3. Remove pre-1.14 artifacts

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by snay2** [comment]
Ran the end-to-end tests on my local machine and they all passed. Not sure why they keep failing in GitHub Actions, but I'm comfortable with merging this once we're ready.

**Comment by snay2** [comment]
Bother. I'm getting the same error locally now that the build here is getting:

`Error: failed to install CRD crds/crd-alertmanager.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

Was there some change to k8s YAML in 1.22? (Possibly the same issue on another repo: https://github.com/sassoftware/esp-kubernetes/issues/20)

**Comment by ngoyal16** [comment]
@snay2 i have fixed it at known places. please check.

**Comment by ngoyal16** [comment]
@snay2 can we use latest version of helm chart for `prometheus-operator` as the current is deprecated already?

**Pull request merged**
