### PR TITLE
Fix custom nodeAffinity via values.yaml

### PR DESCRIPTION
**Pull request by ngoyal16**
Issue #495 

Description of changes:

1. Removed arch affinity from nodeAffinity completely
2. Removed OS node selector from nodeAffinity. As it already exists in nodeSelector

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ngoyal16** [comment]
@bwagner5 as per the issue, peoples are facing  issue with deployment type only not with the dameonsets one. so i guess we can go with this fix.

**Comment by bwagner5** [comment]
@ngoyal16  can you move the fargate anti-affinity to the values.yaml file?

**Comment by ngoyal16** [comment]
\rerun

**Review by snay2 — APPROVED** [review]
LGTM. Thanks!

**Review by bwagner5 — APPROVED** [review]
/lgtm

**Pull request merged**
