### PR TITLE
🥑🤖 v1.14.1 release prep

### PR DESCRIPTION
**Pull request by snay2**
🥑🤖 Auto-generated PR for v1.14.1 release. Updating release versions in repo.

### CODE REVIEW

**Review by brycahta — APPROVED** [review]
/lgtm

**Comment by stevehipwell** [comment]
@brycahta @snay2 @bwagner5 as #540 contained breaking changes shouldn't the chart version have been updated to `0.17.0`? I know that technically any change to a SemVer 2 `v0.x.y` version is a breaking change but it's clearer if the minor version is changed.

**Comment by snay2** [comment]
@stevehipwell Thanks for bringing that to our attention. In hindsight, I should have made this a minor version release (`0.17.0`) instead of a patch release because there were technically breaking changes. But after reviewing it with the team this morning, we feel comfortable leaving the helm chart at `0.16.1` despite those changes.

**Comment by snay2** [comment]
On second thoughts, since the chart hasn't been released to eks-charts yet (https://github.com/aws/eks-charts/pull/675), we're going to take this opportunity to match the version numbers between the chart and the app, and we won't release a chart on version `0.16.1`.

Therefore, the breaking changes for the helm chart refactor will be in the chart version `1.14.1` to match the NTH app version. PR forthcoming...

**Comment by stevehipwell** [comment]
I'd advise against trying to match the chart and app versions, how about chart `v1.0.0`?

**Pull request merged**
