### PR TITLE
Implement scheduled action draining with cancellation support

### PR DESCRIPTION
**Pull request by bwagner5**
Issue #, if available:
https://github.com/aws/aws-node-termination-handler/issues/30

## Description of changes:

** Note this is currently an experimental feature and will be disabled by default until v2.0.0 is released ** 

This PR adds support to cordon and drain K8s nodes when receiving EC2 Instance Maintenance Events originating from the EC2 Instance Metadata Service (IMDS -> 169.254.169.254/latest/meta-data/events/maintenance/scheduled). 

 - Supports cordon and draining at the start time of the maintenance window of a scheduled maintenance event
 - Supports cancelling cordon and draining if EC2 Instance Metadata cancels the maintenance event.
 - Supports uncordoning a node if the maintenance event is a system reboot by adding a label on the node that the aws-node-termination-handler will inspect when starting up. 

## Testing

 - Added a scheduled-maintenance event e2e test that also tests dry-run

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bwagner5** [comment]
Once this PR is approved, I'll open up an eks-charts helm PR to batch sync the changes we've made over the last few PRs (@mattrandallbecker webhooks and @gavinbunney's namespace additions)

**Comment by jaypipes** [comment]
@bwagner5 reviewing this now. But, there are a number of test failures that you should look into. Can't tell from a cursory look whether they are just flakes, but doesn't seem to be.

In addition, go through the test output and look for a variety of warnings and errors that appear to be either ignored or not handled.

Example:

```
/home/travis/build/aws/aws-node-termination-handler/test/k8s-local-cluster-test/../e2e/maintenance-event-test: line 75: POD_EVICTED: unbound variable
```

**Comment by bwagner5** [comment]
I believe I've fixed the tests for K8s 1.11 and 1.12, I'm rerunning them locally now to make sure. The API output is slightly different for 1.11 and 1.12 for the assertion I was doing to verify the regular-pod-test was scheduled and evicted properly.  I fixed the unbound variable output as well. Will sync-up soon.

**Comment by bwagner5** [comment]
Sure, I'll break this into separate PRs

**Comment by bwagner5** [comment]
closing in favor of breaking this into smaller PRs

**Pull request closed without merging**
