### PR TITLE
fix(chart): added missing livenessProbe

### PR DESCRIPTION
**Pull request by MarcusNoble**
Issue #, if available: N/A

Description of changes:

The chart was missing the actual livenessProbe, even though it was defined in the values.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bwagner5** [comment]
LGTM, can you remove the chart version increment? Our automated syncing process will take care of incrementing the version so that it can batch chart changes to a single version change.

**Review by bwagner5 — CHANGES_REQUESTED** [review]
Remove version increment, other than that lgtm

**Comment by MarcusNoble** [comment]
@bwagner5  Done :)

**Review by bwagner5 — APPROVED** [review]
Awesome, thanks! Lgtm

**Comment by MarcusNoble** [comment]
@bwagner5 Would it be possible to get a release published with this fix? It's currently one of the only 3rd party apps in our cluster missing probes.

**Pull request merged**
