### PR TITLE
Remove EOL kubernetes version

### PR DESCRIPTION
**Pull request by ngoyal16**
**Issue #, if available:**

**Description of changes:**

EOL kubernetes version support compatiblity test removed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by snay2 — CHANGES_REQUESTED** [review]
Hey @ngoyal16, thanks for staying on top of these version updates!

Historically, we've kept the 6 most recent k8s versions in the testing matrix. I'm fine with removing `1.17` now, but can you also add `1.23` into the matrix as well?

(Looks like [1.24 should be released next week](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.24#summary) and EKS should be [dropping 1.18 support soon](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar), so we can come back and update this matrix again in a few weeks.)

**Comment by ngoyal16** [comment]
@snay2 Kubernetes v1.18 support is already droped by EKS on 31st march, 2022.

also could you provide the docker kind image url for the v1.23 for testing

**Comment by snay2** [comment]
Good point, we can remove 1.18 as soon as 1.24 is released this month.

The latest minor version of 1.23 available, per https://hub.docker.com/r/kindest/node/tags, is 1.23.5. Here's the image identifier:

```
kindest/node@sha256:1a72748086bc24ed6163de1d1e33cc0e2eb5a1eb5ebffdb15b53c3bcd5376a6f
```

(I got that with this command, if you want to verify:)

```
docker pull kindest/node:v1.23.5 && docker inspect kindest/node:v1.23.5 | jq ".[0].RepoDigests[0]"
```

**Review by snay2 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
