### PR TITLE
Correct instantiation of AWS session object

### LINKED ISSUE #420: Unable to use STS regional endpoint
I'm trying to spin the NTH up using queue mode in an EKS cluster that doesn't have direct internet access but does have VPC endpoints created for (hopefully) every required service.

This isn't the first controller that I've spun up; every previous one I'm using requires patching in the environment variable `AWS_STS_REGIONAL_ENDPOINTS=regional` in order to make them use `sts.<region>.amazonaws.com` instead of the global `sts.amazonaws.com` endpoint. The former endpoint then resolves to the VPC endpoint I've created and authentication is successful.

I'm getting the following logged when running the NTH:
```
2021/04/26 17:09:25 WRN There was a problem monitoring for events error="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 52.94.241.129:443: i/o timeout" event_type=SQS_TERMINATE
2021/04/26 17:11:25 WRN There was a problem monitoring for events error="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 52.46.134.192:443: i/o timeout" event_type=SQS_TERMINATE
```
I've set the above environment variable, and also tried removing the `AWS_ENDPOINT` and `AWS_REGION` variables just in case they were confusing things but the Deployment/Pod doesn't appear to be respecting it.

### PR DESCRIPTION
**Pull request by bodgit**
The region needs to be set on the config object before creating the
session so that things like setting `AWS_STS_REGIONAL_ENDPOINTS` can
take effect.

Also, if credentials cannot be acquired, die at that point instead of
carrying on.

Fixes #420

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by haugenj — APPROVED** [review]
👍 LGTM, thanks!

**Comment by bwagner5** [comment]
I'm good with your changes, but rather than making users specify: `export AWS_STS_REGIONAL_ENDPOINTS regional`  we can just hard code the config to use regional endpoints. I don't think there's a reason to use the global endpoint w/ NTH.  If there's something I'm missing with that assumption, then a second option would be to add the `AWS_STS_REGIONAL_ENDPOINTS` var in the helm chart's values.yaml and default it to `regional`. 

```
cfg := aws.NewConfig().
			WithRegion(nthConfig.AWSRegion).
			WithEndpoint(nthConfig.AWSEndpoint).
			WithSTSRegionalEndpoint(endpoints.RegionalSTSEndpoint)
		sess := session.Must(session.NewSessionWithOptions(session.Options{
			Config:            *cfg,
			SharedConfigState: session.SharedConfigEnable,
		}))
```

**Comment by bodgit** [comment]
It was purely a case of not changing existing behaviour. You can do exactly as you describe and force the regional endpoint when creating the session object; I've seen some controllers/drivers do that. If you're happy to have that slight change in behaviour then I can tweak the PR. That would be one less Kustomization patch I have to have :wink:

**Comment by bwagner5** [comment]
Cool, I’m good with hard coding it in the session! Mind adding to this pr?

**Comment by bodgit** [comment]
Done

**Review by bwagner5 — APPROVED** [review]
nice! Thank you! LGTM

**Pull request merged**
