### PR TITLE
🥑🤖 v1.17.0 release prep

### PR DESCRIPTION
**Pull request by snay2**
🥑🤖 Auto-generated PR for v1.17.0 release. Updating release versions in repo.

### CODE REVIEW

**Comment by snay2** [comment]
Kindly requesting that my fellow maintainers also review my [proposed release notes](https://github.com/aws/aws-node-termination-handler/releases/tag/untagged-50a8566ca6d252b1c8d0) to ensure they are clear and complete enough, especially related to our removal of ASG API calls and reliance on instance tag propagation.

**Comment by AustinSiu** [comment]
> 🧐 Kindly requesting that my fellow maintainers also review my [proposed release notes](https://github.com/aws/aws-node-termination-handler/releases/tag/untagged-50a8566ca6d252b1c8d0) to ensure they are clear and complete enough, especially related to our removal of ASG API calls and reliance on instance tag propagation.

One comment on the following line:
> Remove all calls to ASG APIs. 

Can we rephrase to "Remove all calls to ASG APIs during determination of a managed instance" or similar? Wouldn't want any readers to get confused since we still call ASG APIs for things like [completing ASG Lifecycle Hooks.](https://github.com/aws/aws-node-termination-handler/blob/5fa4dc44925e8028260437bb37e85f75599c7c23/pkg/monitor/sqsevent/sqs-monitor.go#L124)

**Comment by brycahta** [comment]
> 🧐 Kindly requesting that my fellow maintainers also review my [proposed release notes](https://github.com/aws/aws-node-termination-handler/releases/tag/untagged-50a8566ca6d252b1c8d0) to ensure they are clear and complete enough, especially related to our removal of ASG API calls and reliance on instance tag propagation.

Release notes look good to me. I think it could be slightly improved if we elevate the potential breaks to the top, ex:

```
⚠️ Callouts ⚠️
These may be breaking changes depending on setup.

* **Remove all calls to ASG APIs.** If you use ASGs but do not propagate tags to your EC2 instances, since NTH will now only check tags on the instance itself to determine whether NTH should manage that instance.
* **Deprecate CheckASGTagBeforeDraining** config value and replace it with CheckTagBeforeDraining
* **Deprecate ManagedAsgTag** config value and replace it with ManagedTag

**What's Changed**
What's Changed
* Filter managed non-ASG nodes by tag by...
* feat(observability): add eventID to exposed metrics by...
```

**Comment by snay2** [comment]
Thanks @AustinSiu and @brycahta, I'll make those changes.

**Review by brycahta — APPROVED** [review]
/lgtm

**Pull request merged**
