### PR TITLE
Add SQS InterruptionEvent.InstanceType

### PR DESCRIPTION
**Pull request by hari-rad**
Feature - would like to expose the InstanceType also in the webhook notifications

Changes - Updated getNodeInfo to return the InstanceType 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Lu-David** [comment]
Hi @hari-rad  thanks for making this PR. Could you also make sure to make changes to e2e tests to ensure your changes pass? You can also run e2e tests locally using make e2e-test.

**Comment by hari-rad** [comment]
> Hi @hari-rad thanks for making this PR. Could you also make sure to make changes to e2e tests to ensure your changes pass? You can also run e2e tests locally using make e2e-test.

Thanks @Lu-David, I have been trying to figure out how to fix it. Managed to get the e2e webhook-proxy-test running locally now. Will try to debug, thanks. If you have any pointers, please do share, as I fail to understand how the template containing "InstanceType" in the webhook-proxy-test is passing validation now!
```
  --set webhookTemplate="\{\"Content\":\"[NTH][Instance Interruption] InstanceId: \{\{ \.InstanceID \}\} - Node: \{\{ \.NodeName \}\} - InstanceType: \{\{ \.InstanceType \}\} - Kind: \{\{ \.Kind \}\} - Start Time: \{\{ \.StartTime \}\}\"\}"
```

**Comment by hari-rad** [comment]
I had a look at the Contributing process. Please let me know if I need to create an Issue for this.
cc @Lu-David

**Review by Lu-David — APPROVED** [review]

**Comment by Lu-David** [comment]
Yes! We'll include this in our next release! Thanks for contributing!

**Pull request merged**
